name: Basic Android CI

# 1. ¿Cuándo se ejecuta este CI?
on:
  push: # En cada push a estas ramas
    branches: [ main, master ]
  pull_request: # En cada pull request dirigido a estas ramas
    branches: [ main, master ]

# 2. ¿Qué trabajos (jobs) se van a realizar?
jobs:
  # Nombre del job actualizado para reflejar múltiples comprobaciones
  code_quality_checks:
    name: Run Code Quality Checks # Nombre legible actualizado
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Paso para Detekt
      - name: Run Detekt
        run: ./gradlew detekt

      # NUEVO: Paso para Ktlint
      - name: Run Ktlint
        run: ./gradlew ktlintCheck # Ejecuta ktlintCheck en todos los módulos donde esté aplicado

      # Subir informes de Detekt
      - name: Upload Detekt HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-html-reports # Nombre del artefacto actualizado
          path: "**/build/reports/detekt/*.html"

      # OPCIONAL (lo podemos añadir después si quieres):
      # - name: Upload Ktlint SARIF Report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ktlint-sarif-reports
      #     path: "**/build/reports/ktlint/**/ktlint*.sarif" # Ktlint puede generar informes SARIF
